#!/bin/bash

# Define full path to sec_floating_feature.xml
TARGET_FILE="$WORK_DIR/system/system/etc/sec_floating_feature.xml"

if [ ! -f "$TARGET_FILE" ]; then
  echo "! Error: Target file $TARGET_FILE not found."
  exit 1
fi

echo "- Patching floating feature flags in $TARGET_FILE..."

if grep -q "SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_REDUCED_BG_BLUR" "$TARGET_FILE"; then
  sed -i 's/<SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_REDUCED_BG_BLUR>.*<\/SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_REDUCED_BG_BLUR>/<SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_REDUCED_BG_BLUR>TRUE<\/SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_REDUCED_BG_BLUR>/g' "$TARGET_FILE"
else
  sed -i '/<\/SecFloatingFeatureSet>/i \    <SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_REDUCED_BG_BLUR>TRUE<\/SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_REDUCED_BG_BLUR>' "$TARGET_FILE"
fi

# Set performance tier to MidEnd
if grep -q "SEC_FLOATING_FEATURE_GRAPHICS_CONFIG_PERFORMANCE" "$TARGET_FILE"; then
  sed -i 's/<SEC_FLOATING_FEATURE_GRAPHICS_CONFIG_PERFORMANCE>.*<\/SEC_FLOATING_FEATURE_GRAPHICS_CONFIG_PERFORMANCE>/<SEC_FLOATING_FEATURE_GRAPHICS_CONFIG_PERFORMANCE>MidEnd<\/SEC_FLOATING_FEATURE_GRAPHICS_CONFIG_PERFORMANCE>/g' "$TARGET_FILE"
else
  sed -i '/<\/SecFloatingFeatureSet>/i \    <SEC_FLOATING_FEATURE_GRAPHICS_CONFIG_PERFORMANCE>MidEnd<\/SEC_FLOATING_FEATURE_GRAPHICS_CONFIG_PERFORMANCE>' "$TARGET_FILE"
fi

# Disable 3D surface transitions if tag exists
if grep -q "SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_3D_SURFACE_TRANSITION" "$TARGET_FILE"; then
  sed -i 's/<SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_3D_SURFACE_TRANSITION>.*<\/SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_3D_SURFACE_TRANSITION>/<SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_3D_SURFACE_TRANSITION>FALSE<\/SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_3D_SURFACE_TRANSITION>/g' "$TARGET_FILE"
fi

echo "- Successfully applied floating feature blur optimizations."
